/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-11-27 07:35:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;

public final class calendar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/ERP/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1604883783799L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Calendar cal = Calendar.getInstance();
	String strYear = request.getParameter("year");
	String strMonth = request.getParameter("month");
	int year = cal.get(Calendar.YEAR);
	int month = cal.get(Calendar.MONTH);
	int date = cal.get(Calendar.DATE);
	if (strYear != null) {
		year = Integer.parseInt(strYear);
		month = Integer.parseInt(strMonth);
	} else {
	}

	//년도/월 셋팅
	cal.set(year, month, 1);
	int startDay = cal.getMinimum(java.util.Calendar.DATE);
	int endDay = cal.getActualMaximum(java.util.Calendar.DAY_OF_MONTH);
	int start = cal.get(java.util.Calendar.DAY_OF_WEEK);
	int newLine = 0;

	//오늘 날짜 저장.
	Calendar todayCal = Calendar.getInstance();
	SimpleDateFormat sdf = new SimpleDateFormat("yyyMMdd");
	int intToday = Integer.parseInt(sdf.format(todayCal.getTime()));

      out.write("\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<HEAD>\r\n");
      out.write("<TITLE>캘린더</TITLE>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("<meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<script type=\"text/javaScript\" language=\"javascript\"></script>\r\n");
      out.write("<style TYPE=\"text/css\">\r\n");
      out.write("body {\r\n");
      out.write("\tscrollbar-face-color: #F6F6F6;\r\n");
      out.write("\tscrollbar-highlight-color: #bbbbbb;\r\n");
      out.write("\tscrollbar-3dlight-color: #FFFFFF;\r\n");
      out.write("\tscrollbar-shadow-color: #bbbbbb;\r\n");
      out.write("\tscrollbar-darkshadow-color: #FFFFFF;\r\n");
      out.write("\tscrollbar-track-color: #FFFFFF;\r\n");
      out.write("\tscrollbar-arrow-color: #bbbbbb;\r\n");
      out.write("\tmargin-left: \"0px\";\r\n");
      out.write("\tmargin-right: \"0px\";\r\n");
      out.write("\tmargin-top: \"0px\";\r\n");
      out.write("\tmargin-bottom: \"0px\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td {\r\n");
      out.write("\tfont-family: \"돋움\";\r\n");
      out.write("\tfont-size: 9pt;\r\n");
      out.write("\tcolor: #595959;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th {\r\n");
      out.write("\tfont-family: \"돋움\";\r\n");
      out.write("\tfont-size: 9pt;\r\n");
      out.write("\tcolor: #000000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("select {\r\n");
      out.write("\tfont-family: \"돋움\";\r\n");
      out.write("\tfont-size: 9pt;\r\n");
      out.write("\tcolor: #595959;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".divDotText {\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\ttext-overflow: ellipsis;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("A:link {\r\n");
      out.write("\tfont-size: 9pt;\r\n");
      out.write("\tfont-family: \"돋움\";\r\n");
      out.write("\tcolor: #000000;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("A:visited {\r\n");
      out.write("\tfont-size: 9pt;\r\n");
      out.write("\tfont-family: \"돋움\";\r\n");
      out.write("\tcolor: #000000;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("A:active {\r\n");
      out.write("\tfont-size: 9pt;\r\n");
      out.write("\tfont-family: \"돋움\";\r\n");
      out.write("\tcolor: red;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("A:hover {\r\n");
      out.write("\tfont-size: 9pt;\r\n");
      out.write("\tfont-family: \"돋움\";\r\n");
      out.write("\tcolor: red;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</HEAD>\r\n");
      out.write("<BODY>\r\n");
      out.write("\t<form name=\"calendarFrm\" id=\"calendarFrm\" action=\"\" method=\"post\">\r\n");
      out.write("\t\t<DIV id=\"content\" style=\"width: 712px;\">\r\n");
      out.write("\t\t\t<table width=\"100%\" border=\"0\" cellspacing=\"1\" cellpadding=\"1\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td align=\"right\"><input type=\"button\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"javascript:location.href='");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("'\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"오늘\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!--날짜 네비게이션  -->\r\n");
      out.write("\t\t\t<table width=\"100%\" border=\"0\" cellspacing=\"1\" cellpadding=\"1\"\r\n");
      out.write("\t\t\t\tid=\"KOO\" bgcolor=\"#F3F9D7\" style=\"border: 1px solid #CED99C\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td height=\"60\">\r\n");
      out.write("\t\t\t\t\t\t<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td height=\"10\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("?year=");
      out.print(year - 1);
      out.write("&amp;month=");
      out.print(month);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttarget=\"_self\"> <b>&lt;&lt;</b> <!-- 이전해 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t</a> ");

 	if (month > 0) {
 
      out.write(" <ahref\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("?year=");
      out.print(year);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t&amp;month=");
      out.print(month - 1);
      out.write(" \"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttarget=\"_self\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<b>&lt;</b> <!-- 이전달 --> </a> ");

 	} else {
 
      out.write(" <b>&lt;</b> ");

 	}
 
      out.write(" &nbsp;&nbsp; ");
      out.print(year);
      out.write('년');
      out.write(' ');
      out.print(month + 1);
      out.write("월 &nbsp;&nbsp; ");

 	if (month < 11) {
 
      out.write(" <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thref=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("?year=");
      out.print(year);
      out.write("&amp;month=");
      out.print(month + 1);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttarget=\"_self\"> <!-- 다음달 --> <b>&gt;</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a> ");

 	} else {
 
      out.write(" <b>&gt;</b> ");

 	}
 
      out.write(" <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thref=\"");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write("?year=");
      out.print(year + 1);
      out.write("&amp;month=");
      out.print(month);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttarget=\"_self\"> <!-- 다음해 --> <b>&gt;&gt;</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<table border=\"0\" cellspacing=\"1\" cellpadding=\"1\" bgcolor=\"#FFFFFF\">\r\n");
      out.write("\t\t\t\t<THEAD>\r\n");
      out.write("\t\t\t\t\t<TR bgcolor=\"#CECECE\">\r\n");
      out.write("\t\t\t\t\t\t<TD width='100px'>\r\n");
      out.write("\t\t\t\t\t\t\t<DIV align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<font color=\"red\">일</font>\r\n");
      out.write("\t\t\t\t\t\t\t</DIV>\r\n");
      out.write("\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t<TD width='100px'>\r\n");
      out.write("\t\t\t\t\t\t\t<DIV align=\"center\">월</DIV>\r\n");
      out.write("\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t<TD width='100px'>\r\n");
      out.write("\t\t\t\t\t\t\t<DIV align=\"center\">화</DIV>\r\n");
      out.write("\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t<TD width='100px'>\r\n");
      out.write("\t\t\t\t\t\t\t<DIV align=\"center\">수</DIV>\r\n");
      out.write("\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t<TD width='100px'>\r\n");
      out.write("\t\t\t\t\t\t\t<DIV align=\"center\">목</DIV>\r\n");
      out.write("\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t<TD width='100px'>\r\n");
      out.write("\t\t\t\t\t\t\t<DIV align=\"center\">금</DIV>\r\n");
      out.write("\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t<TD width='100px'>\r\n");
      out.write("\t\t\t\t\t\t\t<DIV align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<font color=\"#529dbc\">토</font>\r\n");
      out.write("\t\t\t\t\t\t\t</DIV>\r\n");
      out.write("\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t</THEAD>\r\n");
      out.write("\t\t\t\t<TBODY>\r\n");
      out.write("\t\t\t\t\t<TR class=\"ttt\">\r\n");
      out.write("\t\t\t\t\t\t");

							//처음 빈공란 표시
							for (int index = 1; index < start; index++) {
								out.println("<TD >&nbsp;</TD>");
								newLine++;
							}
							for (int index = 1; index <= endDay; index++) {
								String color = "";
								if (newLine == 0) {
									color = "RED";
								} else if (newLine == 6) {
									color = "#529dbc";
								} else {
									color = "BLACK";
								}
								;
								String sUseDate = Integer.toString(year);
								sUseDate += Integer.toString(month + 1).length() == 1 ? "0" + Integer.toString(month + 1)
										: Integer.toString(month + 1);
								sUseDate += Integer.toString(index).length() == 1 ? "0" + Integer.toString(index)
										: Integer.toString(index);
								int iUseDate = Integer.parseInt(sUseDate);
								String backColor = "#EFEFEF";
								if (iUseDate == intToday) {
									backColor = "#c9c9c9";
								}
								out.println("<TD class='ddd' style='valign:top; align:left; height:92px; bgcolor:" + backColor + "; nowrap'>");
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<font color='");
      out.print(color);
      out.write('\'');
      out.write('>');
      out.write(' ');
      out.print(index);
      out.write("</font>\r\n");
      out.write("\t\t\t\t\t\t");

							out.println("<BR>");
								out.println(iUseDate);
								out.println("<BR>");
								//기능 제거 
								out.println("</TD>");
								newLine++;
								if (newLine == 7) {
									out.println("</TR>");
									if (index <= endDay) {
										out.println("<TR class='ttt'>");
									}
									newLine = 0;
								}
							}
							//마지막 공란 LOOP
							while (newLine > 0 && newLine < 7) {
								out.println("<TD>&nbsp;</TD>");
								newLine++;
							}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t</TBODY>\r\n");
      out.write("\t\t\t</TABLE>\r\n");
      out.write("\t\t</DIV>\r\n");
      out.write("\t</form>\r\n");
      out.write("</BODY>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(\".ttt\").on(\"click\", \".ddd\", function() {\r\n");
      out.write("\t\tlet i = $(this).find(\"font\").html();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\talert(month+\"/\"+i);\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</HTML>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /WEB-INF/views/calendar.jsp(109,41) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/CalendarExam2.jsp");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f1.setParent(null);
    // /WEB-INF/views/calendar.jsp(125,15) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f1.setValue("/CalendarExam2.jsp");
    int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
    if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f2.setParent(null);
    // /WEB-INF/views/calendar.jsp(130,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f2.setValue("/CalendarExam2.jsp");
    int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
    if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f3.setParent(null);
    // /WEB-INF/views/calendar.jsp(140,16) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f3.setValue("/CalendarExam2.jsp");
    int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
    if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f4.setParent(null);
    // /WEB-INF/views/calendar.jsp(147,16) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f4.setValue("/CalendarExam2.jsp");
    int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
    if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
    return false;
  }
}
