/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-11-27 01:38:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class graph_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>구글 차트 라이브러리</title>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://www.gstatic.com/charts/loader.js\"></script>  <!-- 라이브러리 Load -->\r\n");
      out.write("    <script src=\"http://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<select id=\"sel\">\r\n");
      out.write("\t<option value=\"cavg.json\">cavg</option>\r\n");
      out.write("\t<option value=\"savg.json\">savg</option>\r\n");
      out.write("\t<option value=\"dcount.json\">dcount</option>\r\n");
      out.write("</select>\r\n");
      out.write("    <div id=\"chart_div\" style=\"width:1000px; height:500px;\"></div>\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("let title1 = \"강좌별 학생 점수\";\r\n");
      out.write("    changeChart();\r\n");
      out.write("    $(\"#sel\").change(function() {\r\n");
      out.write("    \tif($(\"#sel\").val() == \"cavg.json\") {\r\n");
      out.write("    \t\ttitle1 = \"강좌별 평군 점수\";\r\n");
      out.write("    \t} else if($(\"#sel\").val() == \"savg.json\") {\r\n");
      out.write("    \t\ttitle1 = \"학생별 평균 점수\";\r\n");
      out.write("    \t} else if($(\"#sel\").val() == \"dcount.json\") {\r\n");
      out.write("    \t\ttitle1 = \"학과별 학생수\";\r\n");
      out.write("    \t}\r\n");
      out.write("    \tchangeChart();\r\n");
      out.write("    });\r\n");
      out.write("    function changeChart(){\r\n");
      out.write("    \tvar sel = $(\"#sel\").val();\r\n");
      out.write("        google.charts.load('current', {'packages':['corechart']});\r\n");
      out.write("        google.charts.setOnLoadCallback(drawVisualization);\r\n");
      out.write("       \r\n");
      out.write("        \tfunction drawVisualization() {\r\n");
      out.write("            \t$.ajax({\r\n");
      out.write("                \ttype:\"get\",\r\n");
      out.write("\t                url:sel,\r\n");
      out.write("\t                dataType:\"json\",\r\n");
      out.write("                \tsuccess:function(result){\r\n");
      out.write("//                     var result = [[\"과목\",\"점수\"],[\"국어\",90],[\"영어\",80]];\r\n");
      out.write("                    \tvar data = google.visualization.arrayToDataTable(result); /* 데이터 셋팅 */\r\n");
      out.write("                    \tvar options = { title : title1, seriesType: 'bars' }; /* 옵션 셋팅 */\r\n");
      out.write("                    \tvar chart = new google.visualization.ComboChart(document.getElementById('chart_div'));\r\n");
      out.write("                    \tvar chart1 = new google.visualization.PieChart(document.getElementById('chart_div'));\r\n");
      out.write("                    \tif(sel == \"dcount.json\") {\r\n");
      out.write("                    \t\tchart1.draw(data, options); /* 차트 그리기 */\r\n");
      out.write("                    \t} else {\r\n");
      out.write("                    \t\tchart.draw(data, options); /* 차트 그리기 */\r\n");
      out.write("                    \t}\r\n");
      out.write("                \t}\r\n");
      out.write("            \t});\r\n");
      out.write("        \t}\r\n");
      out.write("        \r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
