/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-12-29 00:47:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.GregorianCalendar;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/ERP/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1604883783799L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>");

   GregorianCalendar cal = new GregorianCalendar();
   String thisYear = cal.get(GregorianCalendar.YEAR)+"";
   String thisMonth = cal.get(GregorianCalendar.MONTH)+1+"";

      out.write("\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.1.1.min.js\"></script>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/style.css\">\n");
      out.write("<style>\n");
      out.write("#profile {\n");
      out.write("   float: left;\n");
      out.write("   margin-top: 30px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#darken-backgrounds {\n");
      out.write("   position: absolute;\n");
      out.write("   top: 0px;\n");
      out.write("   left: 0px;\n");
      out.write("   right: 0px;\n");
      out.write("   height: 100%;\n");
      out.write("   display: none;\n");
      out.write("   background: rgba(0, 0, 0, 0);\n");
      out.write("   z-index: 1000;\n");
      out.write("   overflow: hidden;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#lightboxs {\n");
      out.write("   right: 1350px;\n");
      out.write("   z-index: 1000;\n");
      out.write("   position: fixed;\n");
      out.write("   width: 400px;\n");
      out.write("   margin: 20px auto;\n");
      out.write("   padding: 25px;\n");
      out.write("   border: 1px solid #333333;\n");
      out.write("   border-radius: 5px;\n");
      out.write("   background: white;\n");
      out.write("   box-shadow: 0px 5px 5px rgba(34, 25, 25, 0.4);\n");
      out.write("   text-align: center;\n");
      out.write("}\n");
      out.write("\n");
      out.write("span {\n");
      out.write("   float: left;\n");
      out.write("   color:black;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#btnProfile {\n");
      out.write("   margin-bottom: 50px;\n");
      out.write("   margin-right: 50px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#divicon {\n");
      out.write("   margin-right: 10px;\n");
      out.write("   border: 1px solid lightgray;\n");
      out.write("   margin-top: 100px;\n");
      out.write("   padding: 25px 15px 25px 15px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("img {\n");
      out.write("   margin-left:24%;\n");
      out.write("   align: center;\n");
      out.write("   width: 200px;\n");
      out.write("   height: 120px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("   #thisMonthList {text-align:center; font-size:14px; height:100px; z-index:11111111111111;\n");
      out.write("   color:black; float:right; margin-right:80px; margin-top:10px;}\n");
      out.write("   .type {width:100px;}\n");
      out.write("   .amount {width:120px;}\n");
      out.write("   .rate {width:100px;}\n");
      out.write("   .lastRate {width:100px;}\n");
      out.write("   #mlist{margin-bottom:200px; width:600px; height:100px; float:right;}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("   <div id=\"header\">\n");
      out.write("      <img src=\"../resources/Triple sss.png\" onclick=\"location.href= 'main'\">\n");
      out.write("      <div id=\"mlist\"><table id=\"thisMonthList\"></table></div>\n");
      out.write("         <button type=\"button\" class=\"button\" id=\"profile\"\n");
      out.write("         style=\"width: 60px; float: left; margin-left: 1px;\">\n");
      out.write("         <i class=\"icono-user\"></i>\n");
      out.write("      </button>\n");
      out.write("   <div id=\"darken-backgrounds\">\n");
      out.write("      <div id=\"lightboxs\">\n");
      out.write("         <div id=\"btnId\">\n");
      out.write("            <button type=\"button\" class=\"button\" id=\"btnProfile\"\n");
      out.write("               style=\"width: 60px; float: left; margin-left: 1px;\">\n");
      out.write("               <i class=\"icono-user\"></i>\n");
      out.write("               ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            </button>\n");
      out.write("\n");
      out.write("         </div>\n");
      out.write("         <div id=\"divName\" style=\"margin-left: 20px;\">\n");
      out.write("            ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("         </div>\n");
      out.write("         <div id=\"divicon\">\n");
      out.write("            <button type=\"button\" class=\"button\" id=\"btnChange\"\n");
      out.write("               style=\"width: 100px; color: white; background: #547484; margin-right: 50px; margin-bottom: 20px;\">비밀번호\n");
      out.write("               변경</button>\n");
      out.write("            \n");
      out.write("            <button type=\"button\" class=\"button\" id=\"logout\"\n");
      out.write("               style=\"width: 100px; color: white; background: #547484; margin-right: 50px; padding: 15px 15px 15px 15px;\">로그\n");
      out.write("               아웃</button>\n");
      out.write("         </div>\n");
      out.write("      </div>\n");
      out.write("   </div>   \n");
      out.write("   </div>\n");
      out.write("   \n");
      out.write("<input type=\"hidden\" id=\"value\">\n");
      out.write("</body>\n");
      out.write("<script>\n");
      out.write("var openWin;\n");
      out.write("setInterval(interval, 1000);\n");
      out.write("//비밀번호 변경\n");
      out.write("$(\"#btnChange\").on(\"click\", function() {\n");
      out.write("         openWin = window.open(\"pwUpdate\", \"btnChange\", 'left='\n");
      out.write("               + (screen.availWidth + 660) / 7\n");
      out.write("               + ', width=500px, height=250px');\n");
      out.write("      });\n");
      out.write("      \n");
      out.write("      \n");
      out.write("//로그아웃\n");
      out.write("$(\"#logout\").click(function() {\n");
      out.write("   if(!confirm(\"로그아웃 하시겠습니까?\")) return; \n");
      out.write("      location.href = \"logout\";\n");
      out.write("});\n");
      out.write("\n");
      out.write("$(document).ready(function() {\n");
      out.write("   function showLightBoxs() {\n");
      out.write("      //라이트박스를 보이게 한다. \n");
      out.write("      $(\"#darken-backgrounds\").show();\n");
      out.write("   }\n");
      out.write("   function hideLightBoxs() {\n");
      out.write("      $(\"#darken-backgrounds\").hide();\n");
      out.write("   }\n");
      out.write("   $(\"#darken-backgrounds\").click(function() {\n");
      out.write("      hideLightBoxs();\n");
      out.write("   });\n");
      out.write("   $(\"#profile\").on(\"click\", function() {\n");
      out.write("      showLightBoxs();\n");
      out.write("   });\n");
      out.write("});\n");
      out.write("\n");
      out.write("function interval() {\n");
      out.write("\tif($(\"#value\").val() != \"\") {\n");
      out.write("\t\talert(\"로그인창으로 넘어갑니다.\");\n");
      out.write("\t\tlocation.href=\"logout\";\n");
      out.write("\t}\n");
      out.write("}\n");
      out.write("\n");
      out.write("getThisMonthList();\n");
      out.write("\n");
      out.write("function getThisMonthList() {\n");
      out.write("   $.ajax({\n");
      out.write("      type:\"get\",\n");
      out.write("      url:\"thisMonthList.json\",\n");
      out.write("      success:function(data) {\n");
      out.write("         var addList = \"\";\n");
      out.write("         $(data).each(function() {\n");
      out.write("            var date = \"20\" + this.date;\n");
      out.write("            var salesAmount = this.salesAmount.toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, \",\");\n");
      out.write("            var refundAmount = this.refundAmount.toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, \",\");\n");
      out.write("            var costAmount = this.costAmount.toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, \",\");\n");
      out.write("            var lastSalesAmount = this.lastSalesAmount;\n");
      out.write("            var lastRefundAmount = this.lastRefundAmount;\n");
      out.write("            var lastCostAmount = this.lastCostAmount;\n");
      out.write("            var targetSales = this.targetSales;\n");
      out.write("            var targetCost = this.targetCost;\n");
      out.write("            var strSalesRate = (this.salesAmount/targetSales)*100;\n");
      out.write("            var salesRate = strSalesRate.toFixed(1);\n");
      out.write("            var strCostRate = (this.costAmount/targetCost)*100;\n");
      out.write("            var costRate = strCostRate.toFixed(1);\n");
      out.write("\n");
      out.write("            var strLastSalesRate = (this.salesAmount/this.lastSalesAmount)*100;\n");
      out.write("            var lastSalesRate = strLastSalesRate.toFixed(1);\n");
      out.write("            var strLastRefundRate = (this.refundAmount/lastRefundAmount)*100;\n");
      out.write("            var lastRefundRate = strLastRefundRate.toFixed(1);\n");
      out.write("            var strLastCostRate = (this.costAmount/lastCostAmount)*100;\n");
      out.write("            var lastCostRate = strLastCostRate.toFixed(1);\n");
      out.write("            addList += \"<tr class='tr'><td class='type'>\"+date+\"</td><td class='amount'>이번달 발생 금액</td><td class='rate'>목표 대비 비율</td><td class='lastRate'>전월 대비 비율</td></tr>\";\n");
      out.write("            addList += \"<tr class='tr' id='salesTR'><td class='type'>매출</td><td class='amount'>￦ \"+salesAmount+\"</td><td class='rate' id='salesRate'>\"+salesRate+\"%</td><td class='lastRate' id='salesLastRate'>\"+lastSalesRate+\"%</td></tr>\";\n");
      out.write("            addList += \"<tr class='tr' id='refundTR'><td class='type'>환불</td><td class='amount'>￦ \"+refundAmount+\"</td><td class='rate'></td><td class='lastRate' id='refundLastRate'>\"+lastRefundRate+\"%</td></tr>\";\n");
      out.write("            addList += \"<tr class='tr' id='costTR'><td class='type'>비용</td><td class='amount'>￦ \"+costAmount+\"</td><td class='rate' id='costRate'>\"+costRate+\"%</td><td class='lastRate' id='costLastRate'>\"+lastCostRate+\"%</td></tr>\";\n");
      out.write("         });\n");
      out.write("         $(\"#thisMonthList\").html(addList);\n");
      out.write("         \n");
      out.write("         \n");
      out.write("         $(\"#thisMonthList\").each(function() {\n");
      out.write("            $(this).find(\"#salesTR\").each(function() {\n");
      out.write("               var strSR = $(this).find(\"#salesRate\").html();\n");
      out.write("               var SR = strSR.split(\".\")[0];\n");
      out.write("               if(SR.length >= 3) {\n");
      out.write("                  $(this).find(\"#salesRate\").css(\"color\", \"blue\");\n");
      out.write("               }\n");
      out.write("               \n");
      out.write("               var strLR = $(this).find(\"#salesLastRate\").html();\n");
      out.write("               var LR = strLR.split(\".\")[0];\n");
      out.write("               if(LR.length >= 3) {\n");
      out.write("                  $(this).find(\"#salesLastRate\").css(\"color\", \"blue\");\n");
      out.write("               }\n");
      out.write("            });\n");
      out.write("            \n");
      out.write("            $(this).find(\"#refundTR\").each(function() {\n");
      out.write("               var strLR = $(this).find(\"#refundLastRate\").html();\n");
      out.write("               var LR = strLR.split(\".\")[0];\n");
      out.write("               if(LR.length >= 3) {\n");
      out.write("                  $(this).find(\"#refundLastRate\").css(\"color\", \"red\");\n");
      out.write("               }\n");
      out.write("            });\n");
      out.write("            \n");
      out.write("            $(this).find(\"#costTR\").each(function() {\n");
      out.write("               var strSR = $(this).find(\"#costRate\").html();\n");
      out.write("               var SR = strSR.split(\".\")[0];\n");
      out.write("               if(SR.length >= 3) {\n");
      out.write("                  $(this).find(\"#costRate\").css(\"color\", \"red\");\n");
      out.write("               }\n");
      out.write("               \n");
      out.write("               var strLR = $(this).find(\"#costLastRate\").html();\n");
      out.write("               var LR = strLR.split(\".\")[0];\n");
      out.write("               if(LR.length >= 3) {\n");
      out.write("                  $(this).find(\"#costLastRate\").css(\"color\", \"red\");\n");
      out.write("               }\n");
      out.write("            });\n");
      out.write("         });\n");
      out.write("      }\n");
      out.write("   });\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/views/header.jsp(98,15) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${adminId!=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("                  <span style=\"font-size: 13px; margin-top: 15px;\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${adminId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</span>\n");
        out.write("               ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /WEB-INF/views/header.jsp(105,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${companyName!=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("               <span><b style=\"font-size: 20px;\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${companyName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</b>&nbsp;&nbsp;님\n");
        out.write("                  <br /> 환영합니다. </span>\n");
        out.write("            ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }
}
