/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-12-18 06:37:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/ERP/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1604883783799L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/style.css\">\r\n");
      out.write("<style>\r\n");
      out.write("#profile {\r\n");
      out.write("   float: left;\r\n");
      out.write("   margin-top: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#darken-backgrounds {\r\n");
      out.write("   position: absolute;\r\n");
      out.write("   top: 0px;\r\n");
      out.write("   left: 0px;\r\n");
      out.write("   right: 0px;\r\n");
      out.write("   height: 100%;\r\n");
      out.write("   display: none;\r\n");
      out.write("   background: rgba(0, 0, 0, 0);\r\n");
      out.write("   z-index: 1000;\r\n");
      out.write("   overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#lightboxs {\r\n");
      out.write("   right: 1350px;\r\n");
      out.write("   z-index: 1000;\r\n");
      out.write("   position: fixed;\r\n");
      out.write("   width: 400px;\r\n");
      out.write("   margin: 20px auto;\r\n");
      out.write("   padding: 25px;\r\n");
      out.write("   border: 1px solid #333333;\r\n");
      out.write("   border-radius: 5px;\r\n");
      out.write("   background: white;\r\n");
      out.write("   box-shadow: 0px 5px 5px rgba(34, 25, 25, 0.4);\r\n");
      out.write("   text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("span {\r\n");
      out.write("   float: left;\r\n");
      out.write("   color:black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#btnProfile {\r\n");
      out.write("   margin-bottom: 50px;\r\n");
      out.write("   margin-right: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#divicon {\r\n");
      out.write("   margin-right: 10px;\r\n");
      out.write("   border: 1px solid lightgray;\r\n");
      out.write("   margin-top: 100px;\r\n");
      out.write("   padding: 25px 15px 25px 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("img {\r\n");
      out.write("   margin-right: 7%;\r\n");
      out.write("   align: center;\r\n");
      out.write("   width: 200px;\r\n");
      out.write("   height: 120px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("   <div id=\"header\">\r\n");
      out.write("      <img src=\"../resources/Triple sss.png\" onclick=\"location.href= 'main'\">\r\n");
      out.write("         <button type=\"button\" class=\"button\" id=\"profile\"\r\n");
      out.write("         style=\"width: 60px; float: left; margin-left: 1px;\">\r\n");
      out.write("         <i class=\"icono-user\"></i>\r\n");
      out.write("      </button>\r\n");
      out.write("   <div id=\"darken-backgrounds\">\r\n");
      out.write("      <div id=\"lightboxs\">\r\n");
      out.write("         <div id=\"btnId\">\r\n");
      out.write("            <button type=\"button\" class=\"button\" id=\"btnProfile\"\r\n");
      out.write("               style=\"width: 60px; float: left; margin-left: 1px;\">\r\n");
      out.write("               <i class=\"icono-user\"></i>\r\n");
      out.write("               ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            </button>\r\n");
      out.write("\r\n");
      out.write("         </div>\r\n");
      out.write("         <div id=\"divName\" style=\"margin-left: 20px;\">\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("         </div>\r\n");
      out.write("         <div id=\"divicon\">\r\n");
      out.write("            <button type=\"button\" class=\"button\" id=\"btnChange\"\r\n");
      out.write("               style=\"width: 100px; color: white; background: #547484; margin-right: 50px; margin-bottom: 20px;\">비밀번호\r\n");
      out.write("               변경</button>\r\n");
      out.write("            \r\n");
      out.write("            <button type=\"button\" class=\"button\" id=\"logout\"\r\n");
      out.write("               style=\"width: 100px; color: white; background: #547484; margin-right: 50px; padding: 15px 15px 15px 15px;\">로그\r\n");
      out.write("               아웃</button>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>   \r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("//비밀번호 변경\r\n");
      out.write("$(\"#btnChange\").on(\r\n");
      out.write("      \"click\",\r\n");
      out.write("      function() {\r\n");
      out.write("         window.open(\"pwUpdate\", \"btnChange\", 'left='\r\n");
      out.write("               + (screen.availWidth + 660) / 7\r\n");
      out.write("               + ', width=500px, height=300px');\r\n");
      out.write("      });\r\n");
      out.write("//로그아웃\r\n");
      out.write("$(\"#logout\").click(function() {\r\n");
      out.write("   if (confirm(\"로그아웃 하시겠습니까?\") == true) {\r\n");
      out.write("      alert(\"로그아웃 하셨습니다.\");\r\n");
      out.write("      location.href = \"login\";\r\n");
      out.write("   } else {\r\n");
      out.write("      return;\r\n");
      out.write("   }\r\n");
      out.write("});\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("   function showLightBoxs() {\r\n");
      out.write("      //라이트박스를 보이게 한다. \r\n");
      out.write("      $(\"#darken-backgrounds\").show();\r\n");
      out.write("   }\r\n");
      out.write("   function hideLightBoxs() {\r\n");
      out.write("      $(\"#darken-backgrounds\").hide();\r\n");
      out.write("   }\r\n");
      out.write("   $(\"#darken-backgrounds\").click(function() {\r\n");
      out.write("      hideLightBoxs();\r\n");
      out.write("   });\r\n");
      out.write("   $(\"#profile\").on(\"click\", function() {\r\n");
      out.write("      showLightBoxs();\r\n");
      out.write("   });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(\"#btnChange\").on(\r\n");
      out.write("      \"click\",\r\n");
      out.write("      function() {\r\n");
      out.write("         window.open(\"pwUpdate\", \"btnChange\", 'left='\r\n");
      out.write("               + (screen.availWidth + 660) / 7\r\n");
      out.write("               + ', width=500px, height=300px');\r\n");
      out.write("      });\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/views/header.jsp(85,15) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${adminId!=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                  <span style=\"font-size: 13px; margin-top: 15px;\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${adminId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</span>\r\n");
        out.write("               ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /WEB-INF/views/header.jsp(92,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${companyName!=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("               <span><b style=\"font-size: 20px;\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${companyName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</b>&nbsp;&nbsp;님\r\n");
        out.write("                  <br /> 환영합니다. </span>\r\n");
        out.write("            ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }
}
