/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-12-29 03:01:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class idCheck_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/ERP/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1604883783799L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.1.1.min.js\"></script>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>아이디 중복 체크</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("   <h2>아이디 중복 체크</h2>\n");
      out.write("   <div id=\"checkMsg\"></div>\n");
      out.write("   <table>\n");
      out.write("      <tr>\n");
      out.write("         <td> &nbsp;  \n");
      out.write("                <input type = \"text\" name = \"adminId\" style=\"border:none; width:200px; height:30px; border-bottom:1px solid gray;\" placeholder=\"아이디 입력\" id=\"adminId\">\n");
      out.write("             </td>\n");
      out.write("             <td><input type=\"hidden\" value=\"사용\" id=\"btnUse\"></td>\n");
      out.write("<!--          <td><button type=\"submit\" id=\"btnCheck\">중복확인</button></td> -->\n");
      out.write("      </tr>\n");
      out.write("   </table>\n");
      out.write("      <div id=\"checkMs\"></div>\n");
      out.write("      \n");
      out.write("      <table>\n");
      out.write("      <tr>\n");
      out.write("<!--       <td><input type=\"hidden\" value=\"사용\" id=\"btnUse\"></td> -->\n");
      out.write("      </tr>\n");
      out.write("      </table>\n");
      out.write("      \n");
      out.write("<!--      <a href=\"javascript:window.close()\" style=\"color:gray; margin-left:300px;\">close</a>       -->\n");
      out.write("</body>\n");
      out.write("<script>\n");
      out.write("\n");
      out.write("var check_num = /^[0-9]$/; // 숫자\n");
      out.write("var check_eng = /^[a-zA-Z]$/; // 문자\n");
      out.write("var check_spc = /^[~!@#$%^&*()_+|<>?:{}]$/; // 특수문자\n");
      out.write("var check_kor = /^[ㄱ-ㅎ|ㅏ-ㅣ|가-힣]$/; // 한글체크\n");
      out.write("\n");
      out.write("   //아이디 값 불러오기\n");
      out.write("   //아이디 체크여부 확인\n");
      out.write("\t$(\"#adminId\").focus();\n");
      out.write("\t\n");
      out.write("\t   $(\"#adminId\").on(\"keyup\", function(key) {\n");
      out.write("\t\t  var adminId = $(this).val();\n");
      out.write("\t\t  $.ajax({\n");
      out.write("\t\t\t type:\"post\",\n");
      out.write("\t\t\t url:\"idCheck\",\n");
      out.write("\t\t\t data:{\"adminId\":adminId},\n");
      out.write("\t\t\t success:function(data) {\n");
      out.write("\t\t\t\t if(data == 0) {\n");
      out.write("\t\t\t\t\t if(adminId.length == 0) {\n");
      out.write("\t\t\t\t\t\t $(\"#adminId\").css(\"background\", \"#FF7E7E\"); \n");
      out.write("\t\t\t\t\t }\n");
      out.write("\t\t\t\t\t if(adminId.length != 0) {\n");
      out.write("\t\t\t\t\t\t $(\"#adminId\").css(\"background\", \"#9BFF94\"); \n");
      out.write("\t\t                 \t\tif(key.keyCode == 13) {\n");
      out.write("\t\t                 \t\t\t$(\"#btnUse\").click();\n");
      out.write("\t\t                 \t\t}\n");
      out.write("\t\t\t\t\t }\n");
      out.write("\t\t\t\t }\n");
      out.write("\t\t\t\t if(data == 1) {\n");
      out.write("\t\t\t\t \t$(\"#adminId\").css(\"background\", \"#FF7E7E\"); \n");
      out.write("\t\t\t\t }\n");
      out.write("\t\t\t }\n");
      out.write("\t\t  });\n");
      out.write("\t   });\n");
      out.write("\t\t  $(\"#adminId\").on(\"keyup\", function() {\n");
      out.write("\t\t\t\tvar adminId = $(\"#adminId\").val();\n");
      out.write("\t\t\t\tvar lastValue = adminId.substring(adminId.length-1, adminId.length);\n");
      out.write("\t\t\t\tvar value = adminId.substring(0, adminId.length-1);\n");
      out.write("\t\t\t\tif(adminId.length >= 1) {\n");
      out.write("\t\t\t\t\tif(!check_eng.test(lastValue) && !check_num.test(lastValue)) {\n");
      out.write("\t\t\t\t\t\talert(\"영어와 숫자만 입력할 수 있습니다.\");\n");
      out.write("\t\t\t\t\t\t$(\"#adminId\").val(value);\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t});\n");
      out.write("\t\t  \n");
      out.write("\t\t  $(\"#btnUse\").on(\"click\",function(){\n");
      out.write("\t\t      var id=$(\"#adminId\").val();\n");
      out.write("\t\t      $(\"#adminId\", opener.document).val(id);\n");
      out.write("\t\t      window.close();\n");
      out.write("\t\t   });\n");
      out.write("\t   \n");
      out.write("//       $('#btnCheck').on('click', function(e) {\n");
      out.write("//          e.preventDefault();\n");
      out.write("//          var adminId = $(frm.adminId).val();\n");
      out.write("//          $.ajax({\n");
      out.write("//             type : 'POST',\n");
      out.write("//             url : 'idCheck',\n");
      out.write("//             data : {\n");
      out.write("//                \"adminId\" : adminId\n");
      out.write("//             },\n");
      out.write("//             success : function(data) {\n");
      out.write("//                if(adminId==\"\"){\n");
      out.write("//                   alert(\"아이디를 입력하세요\");\n");
      out.write("//                    $(frm.adminId).focus();\n");
      out.write("//                    return;\n");
      out.write("//                }\n");
      out.write("//                if ((data) == 0) {\n");
      out.write("//                   $('#id').css(\"background\", \"#9BFF94\");\n");
      out.write("//                   $('#btnUse').attr(\"type\", \"button\");\n");
      out.write("//                }else if((data) == 1){\n");
      out.write("//             \t   $('#id').css(\"background\", \"#FF7E7E\");\n");
      out.write("//                   $('#btnUse').attr(\"type\", \"hidden\");\n");
      out.write("//                }\n");
      out.write("//             }\n");
      out.write("//          });\n");
      out.write("//       });\n");
      out.write("   //사용 버튼 누른후 등록화ㅣ면\n");
      out.write("   \n");
      out.write("</script>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
