/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-12-29 00:47:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class lightBox_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.1.1.min.js\"></script>\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js\"></script>\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/gsap/1.16.1/TweenMax.min.js\"></script>\n");
      out.write("<script src=\"https://codepen.io/grayghostvisuals/pen/a08e0d79c150ff5030f9b6afaa137749\"></script>\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<style>\n");
      out.write("#lightBox0 {\n");
      out.write("   position: absolute;\n");
      out.write("   top: 0px;\n");
      out.write("   left: 0px;\n");
      out.write("   right: 0px;\n");
      out.write("   height: 100%;\n");
      out.write("   display: none;\n");
      out.write("   background: rgba(0, 0, 0, 0.1);\n");
      out.write("   z-index: 10000;\n");
      out.write("   overflow: hidden;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#box0 {\n");
      out.write("   height: 50px;\n");
      out.write("   margin: 100px auto;\n");
      out.write("   background: rgba(0, 0, 0, 0);\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write(".attraction {\n");
      out.write("margin:0px auto;\n");
      out.write("margin-top:400px;\n");
      out.write("margin-right:50%;\n");
      out.write("  width: 60px;\n");
      out.write("  height: 60px;\n");
      out.write("  transform: scale(0.25) rotate(-90deg) translateY(-300%);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".attraction svg > * {\n");
      out.write("  fill: #000000;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".attraction svg:nth-child(1) circle {\n");
      out.write("  opacity: 0.06;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".attraction svg:nth-child(2) circle {\n");
      out.write("  opacity: 0.12;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".attraction svg:nth-child(3) circle {\n");
      out.write("  opacity: 0.18;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".attraction svg:nth-child(4) circle {\n");
      out.write("  opacity: 0.24;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".attraction svg:nth-child(5) circle {\n");
      out.write("  opacity: 0.3;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".attraction svg:nth-child(6) circle {\n");
      out.write("  opacity: 0.36;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".attraction svg:nth-child(7) circle {\n");
      out.write("  opacity: 0.42;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".attraction svg:nth-child(8) circle {\n");
      out.write("  opacity: 0.48;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".attraction svg:nth-child(9) circle {\n");
      out.write("  opacity: 0.54;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".attraction svg:nth-child(10) circle {\n");
      out.write("  opacity: 0.6;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".attraction svg:nth-child(11) circle {\n");
      out.write("  opacity: 0.66;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".attraction svg:nth-child(12) circle {\n");
      out.write("  opacity: 0.72;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".attraction svg:nth-child(13) circle {\n");
      out.write("  opacity: 0.78;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div id=\"lightBox0\">\n");
      out.write("\t<div id=\"box0\">\n");
      out.write("\t<div class=\"attraction\">\n");
      out.write("  <svg xmlns=http://www.w3.org/2000/svg viewBox=\"0 0 100 100\"><circle cx=50 cy=50 r=\"42\"/></svg>\n");
      out.write("  <svg xmlns=http://www.w3.org/2000/svg viewBox=\"0 0 100 100\"><circle cx=50 cy=50 r=\"42\"/></svg>\n");
      out.write("  <svg xmlns=http://www.w3.org/2000/svg viewBox=\"0 0 100 100\"><circle cx=50 cy=50 r=\"42\"/></svg>\n");
      out.write("  <svg xmlns=http://www.w3.org/2000/svg viewBox=\"0 0 100 100\"><circle cx=50 cy=50 r=\"42\"/></svg>\n");
      out.write("  <svg xmlns=http://www.w3.org/2000/svg viewBox=\"0 0 100 100\"><circle cx=50 cy=50 r=\"42\"/></svg>\n");
      out.write("  <svg xmlns=http://www.w3.org/2000/svg viewBox=\"0 0 100 100\"><circle cx=50 cy=50 r=\"42\"/></svg>\n");
      out.write("  <svg xmlns=http://www.w3.org/2000/svg viewBox=\"0 0 100 100\"><circle cx=50 cy=50 r=\"42\"/></svg>\n");
      out.write("  <svg xmlns=http://www.w3.org/2000/svg viewBox=\"0 0 100 100\"><circle cx=50 cy=50 r=\"42\"/></svg>\n");
      out.write("  <svg xmlns=http://www.w3.org/2000/svg viewBox=\"0 0 100 100\"><circle cx=50 cy=50 r=\"42\"/></svg>\n");
      out.write("  <svg xmlns=http://www.w3.org/2000/svg viewBox=\"0 0 100 100\"><circle cx=50 cy=50 r=\"42\"/></svg>\n");
      out.write("  <svg xmlns=http://www.w3.org/2000/svg viewBox=\"0 0 100 100\"><circle cx=50 cy=50 r=\"42\"/></svg>\n");
      out.write("  <svg xmlns=http://www.w3.org/2000/svg viewBox=\"0 0 100 100\"><circle cx=50 cy=50 r=\"42\"/></svg>\n");
      out.write("  <svg xmlns=http://www.w3.org/2000/svg viewBox=\"0 0 100 100\"><circle cx=50 cy=50 r=\"42\"/></svg>\n");
      out.write("</div>\n");
      out.write("\t\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("<script>\n");
      out.write("\tvar tl = new TimelineMax({\n");
      out.write("\t  repeat: -1\n");
      out.write("\t});\n");
      out.write("\n");
      out.write("\tvar bezier = [{ x: 0, y: 0, opacity: 0 }, { x: 0, y: 42, opacity: 0 }, { x: 42, y: 42, opacity: 1 }, { x: 42, y: 0, opacity: 1 }, { x: 0, y: 0, opacity: 0 }];\n");
      out.write("\n");
      out.write("\ttl.staggerTo($('.attraction > svg'), 0.8, { bezier: {\n");
      out.write("\t  type: 'thru',\n");
      out.write("\t  values: bezier,\n");
      out.write("\t  curviness: 2\n");
      out.write("\t}, ease: Ease.easeInOut }, 0.09);\n");
      out.write("\t\n");
      out.write("\tfunction lightBox() {\n");
      out.write("\t\t$(\"#lightBox0\").show();\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\tfunction outLightBox() {\n");
      out.write("\t\t$(\"#lightBox0\").hide();\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfunction lightBoxController() {\n");
      out.write("\t\tlightBox();\n");
      out.write("\t\tsetTimeout(outLightBox, 2500);\n");
      out.write("\t}\n");
      out.write("</script>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
