/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-12-29 00:47:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/ERP/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1604883783799L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.1.1.min.js\"></script>\n");
      out.write("<script src=\"http://code.jquery.com/jquery-1.10.2.js\"></script>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Triple S</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/animations.css\">\n");
      out.write("</head>\n");
      out.write("<style>\n");
      out.write("#video {\n");
      out.write("   position: absolute;\n");
      out.write("   top: 0px;\n");
      out.write("   left: 0px;\n");
      out.write("   min-width: 100%;\n");
      out.write("   min-height: 100%;\n");
      out.write("   width: auto;\n");
      out.write("   height: auto;\n");
      out.write("   z-index: -1;\n");
      out.write("   overflow: hidden;\n");
      out.write("}\n");
      out.write("\n");
      out.write("body {\n");
      out.write("   background: #ececec;\n");
      out.write("   padding: 40px 0;\n");
      out.write("   font-family: 'Lato', sans-serif;\n");
      out.write("   color: #444;\n");
      out.write("   text-align: center;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".button-wrapper {\n");
      out.write("   display: inline-block;\n");
      out.write("   margin: 20px 5px;\n");
      out.write("   padding: 40px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dark-button, .dark-button-2 {\n");
      out.write("   background: #333;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".button {\n");
      out.write("   background-color: rgba(300, 300, 300, 0.0);\n");
      out.write("   border: none;\n");
      out.write("   padding: 40px;\n");
      out.write("   cursor: pointer;\n");
      out.write("   display: block;\n");
      out.write("   position: relative;\n");
      out.write("   overflow: hidden;\n");
      out.write("   transition: all .35s ease-in-out .35s;\n");
      out.write("   margin-top: 300px;\n");
      out.write("   width: 200px;\n");
      out.write("   text-align: center;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dark-button .button, .dark-button .button span {\n");
      out.write("   background: #36B4C7;\n");
      out.write("   color: #fff;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dark-button .button:after, .dark-button .button:before, .dark-button .button:hover span\n");
      out.write("   {\n");
      out.write("   background: #fff;\n");
      out.write("   color: #444;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dark-button-2 .button, .dark-button-2 .button span {\n");
      out.write("   background: #333;\n");
      out.write("   color: #fff;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dark-button-2 .button:after, .dark-button-2 .button:before,\n");
      out.write("   .dark-button-2 .button:hover span {\n");
      out.write("   background: #fff;\n");
      out.write("   color: #444;\n");
      out.write("}\n");
      out.write("\n");
      out.write("h2 {\n");
      out.write("   font-family:\"굴림\";\n");
      out.write("   background-color: rgba(300, 300, 300, 0.0);\n");
      out.write("   display: block;\n");
      out.write("   padding: 15px 30px;\n");
      out.write("   z-index: 100;\n");
      out.write("   position: relative;\n");
      out.write("   transition: all .35s ease-in-out .35s;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".button:hover h2 {\n");
      out.write("   background: #36B4C7;\n");
      out.write("   color: #fff;\n");
      out.write("   transition: all .35s ease-in-out .35s;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".button:after {\n");
      out.write("   bottom: -100%;\n");
      out.write("   right: -100%;\n");
      out.write("   content: \"\";\n");
      out.write("   width: 100%;\n");
      out.write("   height: 100%;\n");
      out.write("   position: absolute;\n");
      out.write("   background: #36B4C7;\n");
      out.write("   transition: all .35s ease-in-out .5s;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".button:hover:after {\n");
      out.write("   right: 0;\n");
      out.write("   bottom: 0;\n");
      out.write("   transition: all ease-in-out .35s;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".button:before {\n");
      out.write("   top: -100%;\n");
      out.write("   left: -100%;\n");
      out.write("   content: \"\";\n");
      out.write("   width: 100%;\n");
      out.write("   height: 100%;\n");
      out.write("   position: absolute;\n");
      out.write("   background: #36B4C7;\n");
      out.write("   transition: all .35s ease-in-out .5s;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".button:hover:before {\n");
      out.write("   left: 0;\n");
      out.write("   top: 0;\n");
      out.write("   transition: all ease-in-out .35s;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#darken-background {\n");
      out.write("   position: absolute;\n");
      out.write("   top: 0px;\n");
      out.write("   left: 0px;\n");
      out.write("   right: 0px;\n");
      out.write("   height: 100%;\n");
      out.write("   display: none;\n");
      out.write("   background: rgba(0, 0, 0, 0.5);\n");
      out.write("   z-index: 10000;\n");
      out.write("   overflow-y: scroll;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#lightbox {\n");
      out.write("   width: 600px;\n");
      out.write("   height: 600px;\n");
      out.write("   margin: 20px auto;\n");
      out.write("   border: 1px solid #333333;\n");
      out.write("   border-radius: 5px;\n");
      out.write("   background: white;\n");
      out.write("   box-shadow: 0px 5px 5px rgba(34, 25, 25, 0.4);\n");
      out.write("   \n");
      out.write("}\n");
      out.write("\n");
      out.write(".box {\n");
      out.write("   margin: 10px;\n");
      out.write("   float: left;\n");
      out.write("}\n");
      out.write("#divCenter{margin-left: 20px; margin:100px;}\n");
      out.write(" #frm{border:1px solid #F1F3F2;}\n");
      out.write(" td{padding:20px 10px 10px 15px;}\n");
      out.write("   \n");
      out.write("   #mainlogin {\n");
      out.write("  width: 500px;\n");
      out.write("  height: 80px;\n");
      out.write("  margin-top:30px;\n");
      out.write("  font-family: 'Roboto', sans-serif;\n");
      out.write("  font-size: 11px;\n");
      out.write("  text-transform: uppercase;\n");
      out.write("  letter-spacing: 2.5px;\n");
      out.write("  font-weight: 500;\n");
      out.write("  color: white;\n");
      out.write("  background-color:#597484;\n");
      out.write("  border: none;\n");
      out.write("  border-radius: 45px;\n");
      out.write("  box-shadow: 0px 8px 15px rgba(0, 0, 0, 0.1);\n");
      out.write("  transition: all 0.3s ease 0s;\n");
      out.write("  cursor: pointer;\n");
      out.write("  outline: none;\n");
      out.write("  }\n");
      out.write("\n");
      out.write(" #mainlogin:hover {\n");
      out.write("  background-color: black;\n");
      out.write("  box-shadow: 0px 15px 20px rgba;\n");
      out.write("  color: #fff;\n");
      out.write("  transform: translateY(-7px);\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("*:focus { outline: none; }\n");
      out.write("</style>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("   <video id=\"video\" preload=\"auto\" autoplay=\"true\" loop=\"loop\"\n");
      out.write("      muted=\"muted\" volume=\"0\"> <source src=\"../resources/ask.mp4\">\n");
      out.write("   </source> </video>\n");
      out.write("\n");
      out.write("   <div class=\"light-button button-wrapper\">\n");
      out.write("      <div class=\"button\" onclick=\"location.href='company'\">\n");
      out.write("\n");
      out.write("         <h2 style=\"color: white; text-align:center;\">Registration</h2>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("   </div>\n");
      out.write("\n");
      out.write("   <div class=\"light-button button-wrapper\">\n");
      out.write("      <div class=\"button\" onclick=\"showLogin();\">\n");
      out.write("\n");
      out.write("         <h2 style=\"color: white; text-align: center;\">\n");
      out.write("\n");
      out.write("            Login \n");
      out.write("         </h2>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("   </div>\n");
      out.write(" <!--라이트 박스-->\n");
      out.write(" <div id=\"darken-background\">\n");
      out.write(" <div id=\"divCenter\">\n");
      out.write(" <div id=\"lightbox\" class=\"light-button button-wrapper\">\n");
      out.write("    <button id=\"btnCancell\" style=\"border:0; background:white; font-size:40px; float:left; color:gray;\">X</button>\n");
      out.write("    <h1 style=\"font-size:50px; margin-top:20px;\">LOGIN</h1>\n");
      out.write("   <form name=\"frm\" action=\"loginok\" method=\"post\" style=\"margin-top:100px;\">\n");
      out.write("      <table>\n");
      out.write("         <tr>\n");
      out.write("            <td width=100 style=\"font-size:30px;\">ID</td>\n");
      out.write("            <td width=200><input type=\"text\" name=\"adminId\" style=\"border:none; width:300px; height:50px;\n");
      out.write("             border-bottom:1px solid gray;font-size:20px;\" placeholder=\"아이디 입력\" id=\"id\"></td>\n");
      out.write("         </tr>\n");
      out.write("         <tr>\n");
      out.write("            <td width=100 style=\"font-size:30px\">PASSWORD</td>\n");
      out.write("            <td width=200><input type=\"password\" name=\"adminPassword\" style=\"border:none; height:50px;\n");
      out.write("             width:300px; border-bottom:1px solid gray; font-size:20px;\" placeholder=\"비밀번호 입력\"></td>\n");
      out.write("         </tr>\n");
      out.write("         <tr>\n");
      out.write("         <td colspan=2>\n");
      out.write("<!--              <input type=\"checkbox\" name=\"chkLogin\"  style=\"margin-left:360px; margin-bottom:50px; float:left;\">Keep Login<br/> -->\n");
      out.write("            \n");
      out.write("            <input type=\"submit\" id=\"mainlogin\" value=\"Login\" style=\"margin-left:20px; font-size:30px;\"\n");
      out.write("            ></td>\n");
      out.write("            \n");
      out.write("         </tr>\n");
      out.write("      </table>\n");
      out.write("   </form>\n");
      out.write("   </div>\n");
      out.write("      </div>\n");
      out.write(" </div>\n");
      out.write("</body>\n");
      out.write("<script>\n");
      out.write("\n");
      out.write("   $(\"#btnCancell\").on(\"click\",function(){\n");
      out.write("      location.href = \"login\";\n");
      out.write("      \n");
      out.write("   });\n");
      out.write("   function showLogin(){\n");
      out.write("      $(\"#darken-background\").show();\n");
      out.write("      $(\"#id\").focus();\n");
      out.write("   }\n");
      out.write("\n");
      out.write("   $(frm).submit(function(e) {\n");
      out.write("      e.preventDefault();\n");
      out.write("      var adminId = $(frm.adminId).val();\n");
      out.write("      var adminPassword = $(frm.adminPassword).val();\n");
      out.write("      var chkLogin = $(frm.chkLogin).is(\":checked\") ? true : false;\n");
      out.write("      $.ajax({\n");
      out.write("\n");
      out.write("         type : \"post\",\n");
      out.write("         url : \"mainlogin\",\n");
      out.write("         data : {\n");
      out.write("            \"adminId\" : adminId,\n");
      out.write("            \"adminPassword\" : adminPassword,\n");
      out.write("            \"chkLogin\" : chkLogin\n");
      out.write("         },\n");
      out.write("         success : function(data) {\n");
      out.write("            if (data == 0) {\n");
      out.write("               alert(\"아이디를 입력하세요.\");\n");
      out.write("            } else if (data == 2) {\n");
      out.write("               alert(\"비밀번호가 올바르지 않습니다.\");\n");
      out.write("            } else if (data == 1) {\n");
      out.write("//                frm.submit();\n");
      out.write("               location.href = \"main\";\n");
      out.write("            }\n");
      out.write("         }\n");
      out.write("\n");
      out.write("      });\n");
      out.write("\n");
      out.write("   });\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
