/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-12-24 00:49:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class pwUpdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("#oriTbl, #tbl{padding:10px 10px 5px 10px; margin-left:120px;}\r\n");
      out.write("td {\r\n");
      out.write("   padding: 5px 5px 5px 5px;\r\n");
      out.write("   font-size:17px;\r\n");
      out.write("}\r\n");
      out.write("#lightBox {\r\n");
      out.write("   position: absolute;\r\n");
      out.write("   top: 0px;\r\n");
      out.write("   left: 0px;\r\n");
      out.write("   right: 0px;\r\n");
      out.write("   height: 100%;\r\n");
      out.write("   display: none;\r\n");
      out.write("   background: rgba(0, 0, 0, 0.3);\r\n");
      out.write("   z-index: 10000;\r\n");
      out.write("   overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#box {\r\n");
      out.write("   margin: 50px auto;\r\n");
      out.write("   background: rgba(0, 0, 0, 0.5);\r\n");
      out.write("}\r\n");
      out.write("#text {text-size:15px; color:red; margin-left:140px;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<table id=\"oriTbl\">\r\n");
      out.write("<tr style=\"margin-right:10px;\">\r\n");
      out.write("      <td><input type=\"password\" style=\"border:none; width:200px; height:30px; border-bottom:1px solid gray;\" placeholder=\"현재 비밀번호 확인\" id=\"oriPwChk\"></td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr style=\"margin-right:10px;\"><td><input type=\"button\" value=\"확인\" id=\"chk\" style=\"margin-top:10px; margin-left:170px;\"></td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<form name=\"frm\" action=\"pwUpdate\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("<table id=\"tbl\">\r\n");
      out.write("   <tr class=\"register\" style=\"margin-right:10px;\">\r\n");
      out.write("      <td><input type=\"password\" name=\"oriPw\" style=\"border:none; width:200px; height:30px; border-bottom:1px solid gray;\" placeholder=\"현재 비밀번호\" id=\"oriPw\"></td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr class=\"register\" style=\"margin-right:10px;\">\r\n");
      out.write("      <td class=\"pw\"><input type=\"password\" name=\"newPw\" style=\"border:none; width:200px; height:30px; border-bottom:1px solid gray;\" placeholder=\"새 비밀번호\" id=\"pw\"></td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr class=\"register\" style=\"margin-right:10px;\">\r\n");
      out.write("      <td class=\"pwChk\"><input type=\"password\" name=\"adminPassword\" style=\"border:none; width:200px; height:30px; border-bottom:1px solid gray;\" placeholder=\"비밀번호 확인\" id=\"pwChk\"></td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   \r\n");
      out.write("   <tr>\r\n");
      out.write("   <td><input type=\"submit\" name=\"btnSave\" value=\"저장\" style=\"margin-top:10px; margin-left:170px;\"> </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<div id=\"lightBox\">\r\n");
      out.write("\t<div id=\"box\">\r\n");
      out.write("\t\t<div id=\"text\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("$(\"#tbl\").hide();\r\n");
      out.write("$(\"#oriPwChk\").focus();\r\n");
      out.write("\r\n");
      out.write("$(\"#oriPwChk\").keyup(function(key) {\r\n");
      out.write("\t$(this).css(\"background\", \"white\");\r\n");
      out.write("\tif(key.keyCode == 13) {\r\n");
      out.write("\t\t$(\"#chk\").click();\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(\"#chk\").on(\"click\", function() {\r\n");
      out.write("\tvar pwp = $(this).parent().parent().parent().find(\"#oriPwChk\");\r\n");
      out.write("\tvar pw = $(this).parent().parent().parent().find(\"#oriPwChk\").val();\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype:\"get\",\r\n");
      out.write("\t\turl:\"pwChk.json\",\r\n");
      out.write("\t\tdata:{\"password\":pw},\r\n");
      out.write("\t\tsuccess:function(data) {\r\n");
      out.write("\t\t\tif(data == 0) {\r\n");
      out.write("\t\t\t\t$(\"#oriTbl\").hide();\r\n");
      out.write("\t\t\t\t$(\"#tbl\").show();\r\n");
      out.write("\t\t\t\t$(\"#oriPw\").focus();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(data == 1) {\r\n");
      out.write("\t\t\t\tpwp.css(\"background\", \"red\");\r\n");
      out.write("\t\t\t\tpwp.focus();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(\"#pw\").keyup(function() {\r\n");
      out.write("\tvar pwcp = $(this).parent().parent().parent().find(\".pwChk\").find(\"#pwChk\");\r\n");
      out.write("\tvar pw = $(this).val();\r\n");
      out.write("\tvar pwChk = pwcp.val();\r\n");
      out.write("\tif(pw != pwChk) {\r\n");
      out.write("\t\tpwcp.css(\"background\", \"#FF7E7E\");\r\n");
      out.write("\t\t$(\"#pw\").css(\"background\", \"#FF7E7E\");\r\n");
      out.write("\t}\r\n");
      out.write("\tif(pw == pwChk) {\r\n");
      out.write("\t\tpwcp.css(\"background\", \"#9BFF94\");\r\n");
      out.write("\t\t$(\"#pw\").css(\"background\", \"#9BFF94\");\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(\"#pwChk\").keyup(function() {\r\n");
      out.write("\tvar pwp = $(this).parent().parent().parent().find(\".pw\").find(\"#pw\");\r\n");
      out.write("\tvar pw = pwp.val();\r\n");
      out.write("\tvar pwChk = $(this).val();\r\n");
      out.write("\tif(pw != pwChk) {\r\n");
      out.write("\t\tpwp.css(\"background\", \"#FF7E7E\");\r\n");
      out.write("\t\t$(this).css(\"background\", \"#FF7E7E\");\r\n");
      out.write("\t}\r\n");
      out.write("\tif(pw == pwChk) {\r\n");
      out.write("\t\tpwp.css(\"background\", \"#9BFF94\");\r\n");
      out.write("\t\t$(this).css(\"background\", \"#9BFF94\");\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(\"#pwChk\").focusout(function() {\r\n");
      out.write("\tvar pwChk = $(this).val();\r\n");
      out.write("\tvar pw = $(this).parent().parent().parent().find(\".pw\").find(\"#pw\").val();\r\n");
      out.write("\tif(pwChk != pw) {\r\n");
      out.write("\t\t$(\"#text\").html(\"비밀번호가 일치하지 않습니다.\");\r\n");
      out.write("\t\t  lightBox();\r\n");
      out.write("\t\t  setTimeout(outLightBox, 1000);\r\n");
      out.write("\t\t  $(\"#pw\").focus();\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//저장 눌렀을때\r\n");
      out.write("\r\n");
      out.write("$(frm.btnSave).click(function(e){\r\n");
      out.write("   e.preventDefault();\r\n");
      out.write("var oriPw=$(frm.oriPw).val();\r\n");
      out.write("var newPw=$(frm.newPw).val();\r\n");
      out.write("var adminPassword=$(frm.adminPassword).val();\r\n");
      out.write("   if(oriPw.trim()==\"\"){\r\n");
      out.write("\t   \t$(\"#text\").html(\"현재 비밀번호를 입력하세요.\");\r\n");
      out.write("\t\t  lightBox();\r\n");
      out.write("\t\t  setTimeout(outLightBox, 1000);\r\n");
      out.write("\t\t  frm.oriPw.focus();\r\n");
      out.write("   }else if(newPw.trim()==\"\"){\r\n");
      out.write("\t   $(\"#text\").html(\"새 비밀번호를 입력하세요.\");\r\n");
      out.write("\t\t  lightBox();\r\n");
      out.write("\t\t  setTimeout(outLightBox, 1000);\r\n");
      out.write("      \t\tfrm.newPw.focus();\r\n");
      out.write("   }else if(adminPassword.trim()==\"\"){\r\n");
      out.write("\t   $(\"#text\").html(\"확인하실 비밀번호를 입력하세요.\");\r\n");
      out.write("\t\t  lightBox();\r\n");
      out.write("\t\t  setTimeout(outLightBox, 1000);\r\n");
      out.write("      \t\tfrm.adminPassword.focus();\r\n");
      out.write("   }else{\r\n");
      out.write("\t   $.ajax({\r\n");
      out.write("\t\t  type:\"get\",\r\n");
      out.write("\t\t  url:\"pwChk.json\",\r\n");
      out.write("\t\t  data:{\"password\":oriPw},\r\n");
      out.write("\t\t  success:function(data) {\r\n");
      out.write("\t\t\t  if(data == 1) {\r\n");
      out.write("\t\t\t\t  $(\"#text\").html(\"비밀번호가 일치하지 않습니다.\");\r\n");
      out.write("\t\t\t\t  lightBox();\r\n");
      out.write("\t\t\t\t  setTimeout(outLightBox, 1000);\r\n");
      out.write("\t\t\t\t  $(\"#oriPw\").focus();\r\n");
      out.write("\t\t\t  }\r\n");
      out.write("\t\t\t  if(data == 0) {\r\n");
      out.write("\t\t\t\t  $.ajax({\r\n");
      out.write("\t\t\t\t         type:\"post\",\r\n");
      out.write("\t\t\t\t         url:\"pwUpdate\",\r\n");
      out.write("\t\t\t\t         data:{\"adminPassword\":adminPassword},\r\n");
      out.write("\t\t\t\t         success:function(){\r\n");
      out.write("\t\t\t\t            if(!confirm(\"등록하시겠습니까?\"))return;\r\n");
      out.write("\t\t\t\t            frm.submit();\r\n");
      out.write("\t\t\t\t            alert(\"변경한 비밀번호로 다시 로그인해주세요.\");\r\n");
      out.write("\t\t\t\t            opener.document.getElementById(\"value\").value = \"logout\";\r\n");
      out.write("\t\t\t\t            window.close();\r\n");
      out.write("\t\t\t\t         }\r\n");
      out.write("\t\t\t\t      });\r\n");
      out.write("\t\t\t  }\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t   });\r\n");
      out.write("   }\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function lightBox() {\r\n");
      out.write("\t$(\"#lightBox\").show();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function outLightBox() {\r\n");
      out.write("\t$(\"#lightBox\").hide();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("         </script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
