/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-12-30 04:54:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class pwUpdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.1.1.min.js\"></script>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<style>\n");
      out.write("#oriTbl, #tbl{padding:10px 10px 5px 10px; margin-left:120px;}\n");
      out.write("td {\n");
      out.write("   padding: 5px 5px 5px 5px;\n");
      out.write("   font-size:17px;\n");
      out.write("}\n");
      out.write("#lightBox {\n");
      out.write("   position: absolute;\n");
      out.write("   top: 0px;\n");
      out.write("   left: 0px;\n");
      out.write("   right: 0px;\n");
      out.write("   height: 100%;\n");
      out.write("   display: none;\n");
      out.write("   background: rgba(0, 0, 0, 0.3);\n");
      out.write("   z-index: 10000;\n");
      out.write("   overflow: hidden;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#box {\n");
      out.write("   margin: 50px auto;\n");
      out.write("   background: rgba(0, 0, 0, 0.5);\n");
      out.write("}\n");
      out.write("#text {text-size:15px; color:red; margin-left:140px;}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<table id=\"oriTbl\">\n");
      out.write("<tr style=\"margin-right:10px;\">\n");
      out.write("      <td><input type=\"password\" style=\"border:none; width:200px; height:30px; border-bottom:1px solid gray;\" placeholder=\"현재 비밀번호 확인\" id=\"oriPwChk\"></td>\n");
      out.write("   </tr>\n");
      out.write("   <tr style=\"margin-right:10px;\"><td><input type=\"button\" value=\"확인\" id=\"chk\" style=\"margin-top:10px; margin-left:170px;\"></td></tr>\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("<form name=\"frm\" action=\"pwUpdate\" method=\"post\">\n");
      out.write("\n");
      out.write("<table id=\"tbl\">\n");
      out.write("   <tr class=\"register\" style=\"margin-right:10px;\">\n");
      out.write("      <td><input type=\"password\" name=\"oriPw\" style=\"border:none; width:200px; height:30px; border-bottom:1px solid gray;\" placeholder=\"현재 비밀번호\" id=\"oriPw\"></td>\n");
      out.write("   </tr>\n");
      out.write("   <tr class=\"register\" style=\"margin-right:10px;\">\n");
      out.write("      <td class=\"pw\"><input type=\"password\" name=\"newPw\" style=\"border:none; width:200px; height:30px; border-bottom:1px solid gray;\" placeholder=\"새 비밀번호\" id=\"pw\"></td>\n");
      out.write("   </tr>\n");
      out.write("   <tr class=\"register\" style=\"margin-right:10px;\">\n");
      out.write("      <td class=\"pwChk\"><input type=\"password\" name=\"adminPassword\" style=\"border:none; width:200px; height:30px; border-bottom:1px solid gray;\" placeholder=\"비밀번호 확인\" id=\"pwChk\"></td>\n");
      out.write("   </tr>\n");
      out.write("   \n");
      out.write("   <tr>\n");
      out.write("   <td><input type=\"submit\" name=\"btnSave\" value=\"저장\" style=\"margin-top:10px; margin-left:170px;\"> </td>\n");
      out.write("   </tr>\n");
      out.write("</table>\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("<div id=\"lightBox\">\n");
      out.write("\t<div id=\"box\">\n");
      out.write("\t\t<div id=\"text\"></div>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("<script>\n");
      out.write("$(\"#tbl\").hide();\n");
      out.write("$(\"#oriPwChk\").focus();\n");
      out.write("\n");
      out.write("$(\"#oriPwChk\").keyup(function(key) {\n");
      out.write("\t$(this).css(\"background\", \"white\");\n");
      out.write("\tif(key.keyCode == 13) {\n");
      out.write("\t\t$(\"#chk\").click();\n");
      out.write("\t}\n");
      out.write("});\n");
      out.write("\n");
      out.write("$(\"#chk\").on(\"click\", function() {\n");
      out.write("\tvar pwp = $(this).parent().parent().parent().find(\"#oriPwChk\");\n");
      out.write("\tvar pw = $(this).parent().parent().parent().find(\"#oriPwChk\").val();\n");
      out.write("\t$.ajax({\n");
      out.write("\t\ttype:\"get\",\n");
      out.write("\t\turl:\"pwChk.json\",\n");
      out.write("\t\tdata:{\"password\":pw},\n");
      out.write("\t\tsuccess:function(data) {\n");
      out.write("\t\t\tif(data == 0) {\n");
      out.write("\t\t\t\t$(\"#oriTbl\").hide();\n");
      out.write("\t\t\t\t$(\"#tbl\").show();\n");
      out.write("\t\t\t\t$(\"#oriPw\").focus();\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tif(data == 1) {\n");
      out.write("\t\t\t\tpwp.css(\"background\", \"red\");\n");
      out.write("\t\t\t\tpwp.focus();\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t});\n");
      out.write("});\n");
      out.write("\n");
      out.write("$(\"#pw\").keyup(function() {\n");
      out.write("\tvar pwcp = $(this).parent().parent().parent().find(\".pwChk\").find(\"#pwChk\");\n");
      out.write("\tvar pw = $(this).val();\n");
      out.write("\tvar pwChk = pwcp.val();\n");
      out.write("\tif(pw != pwChk) {\n");
      out.write("\t\tpwcp.css(\"background\", \"#FF7E7E\");\n");
      out.write("\t\t$(\"#pw\").css(\"background\", \"#FF7E7E\");\n");
      out.write("\t}\n");
      out.write("\tif(pw == pwChk) {\n");
      out.write("\t\tpwcp.css(\"background\", \"#9BFF94\");\n");
      out.write("\t\t$(\"#pw\").css(\"background\", \"#9BFF94\");\n");
      out.write("\t}\n");
      out.write("});\n");
      out.write("\n");
      out.write("$(\"#pwChk\").keyup(function() {\n");
      out.write("\tvar pwp = $(this).parent().parent().parent().find(\".pw\").find(\"#pw\");\n");
      out.write("\tvar pw = pwp.val();\n");
      out.write("\tvar pwChk = $(this).val();\n");
      out.write("\tif(pw != pwChk) {\n");
      out.write("\t\tpwp.css(\"background\", \"#FF7E7E\");\n");
      out.write("\t\t$(this).css(\"background\", \"#FF7E7E\");\n");
      out.write("\t}\n");
      out.write("\tif(pw == pwChk) {\n");
      out.write("\t\tpwp.css(\"background\", \"#9BFF94\");\n");
      out.write("\t\t$(this).css(\"background\", \"#9BFF94\");\n");
      out.write("\t}\n");
      out.write("});\n");
      out.write("\n");
      out.write("$(\"#pwChk\").focusout(function() {\n");
      out.write("\tvar pwChk = $(this).val();\n");
      out.write("\tvar pw = $(this).parent().parent().parent().find(\".pw\").find(\"#pw\").val();\n");
      out.write("\tif(pwChk != pw) {\n");
      out.write("\t\t$(\"#text\").html(\"비밀번호가 일치하지 않습니다.\");\n");
      out.write("\t\t  lightBox();\n");
      out.write("\t\t  setTimeout(outLightBox, 1000);\n");
      out.write("\t\t  $(\"#pw\").focus();\n");
      out.write("\t}\n");
      out.write("});\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("//저장 눌렀을때\n");
      out.write("\n");
      out.write("$(frm.btnSave).click(function(e){\n");
      out.write("   e.preventDefault();\n");
      out.write("var oriPw=$(frm.oriPw).val();\n");
      out.write("var newPw=$(frm.newPw).val();\n");
      out.write("var adminPassword=$(frm.adminPassword).val();\n");
      out.write("   if(oriPw.trim()==\"\"){\n");
      out.write("\t   \t$(\"#text\").html(\"현재 비밀번호를 입력하세요.\");\n");
      out.write("\t\t  lightBox();\n");
      out.write("\t\t  setTimeout(outLightBox, 1000);\n");
      out.write("\t\t  frm.oriPw.focus();\n");
      out.write("   }else if(newPw.trim()==\"\"){\n");
      out.write("\t   $(\"#text\").html(\"새 비밀번호를 입력하세요.\");\n");
      out.write("\t\t  lightBox();\n");
      out.write("\t\t  setTimeout(outLightBox, 1000);\n");
      out.write("      \t\tfrm.newPw.focus();\n");
      out.write("   }else if(adminPassword.trim()==\"\"){\n");
      out.write("\t   $(\"#text\").html(\"확인하실 비밀번호를 입력하세요.\");\n");
      out.write("\t\t  lightBox();\n");
      out.write("\t\t  setTimeout(outLightBox, 1000);\n");
      out.write("      \t\tfrm.adminPassword.focus();\n");
      out.write("   }else{\n");
      out.write("\t   $.ajax({\n");
      out.write("\t\t  type:\"get\",\n");
      out.write("\t\t  url:\"pwChk.json\",\n");
      out.write("\t\t  data:{\"password\":oriPw},\n");
      out.write("\t\t  success:function(data) {\n");
      out.write("\t\t\t  if(data == 1) {\n");
      out.write("\t\t\t\t  $(\"#text\").html(\"비밀번호가 일치하지 않습니다.\");\n");
      out.write("\t\t\t\t  lightBox();\n");
      out.write("\t\t\t\t  setTimeout(outLightBox, 1000);\n");
      out.write("\t\t\t\t  $(\"#oriPw\").focus();\n");
      out.write("\t\t\t  }\n");
      out.write("\t\t\t  if(data == 0) {\n");
      out.write("\t\t\t\t  $.ajax({\n");
      out.write("\t\t\t\t         type:\"post\",\n");
      out.write("\t\t\t\t         url:\"pwUpdate\",\n");
      out.write("\t\t\t\t         data:{\"adminPassword\":adminPassword},\n");
      out.write("\t\t\t\t         success:function(){\n");
      out.write("\t\t\t\t            if(!confirm(\"등록하시겠습니까?\"))return;\n");
      out.write("\t\t\t\t            frm.submit();\n");
      out.write("\t\t\t\t            alert(\"변경한 비밀번호로 다시 로그인해주세요.\");\n");
      out.write("\t\t\t\t            opener.document.getElementById(\"value\").value = \"logout\";\n");
      out.write("\t\t\t\t            window.close();\n");
      out.write("\t\t\t\t         }\n");
      out.write("\t\t\t\t      });\n");
      out.write("\t\t\t  }\n");
      out.write("\t\t  }\n");
      out.write("\t   });\n");
      out.write("   }\n");
      out.write("});\n");
      out.write("\n");
      out.write("function lightBox() {\n");
      out.write("\t$(\"#lightBox\").show();\n");
      out.write("}\n");
      out.write("\n");
      out.write("function outLightBox() {\n");
      out.write("\t$(\"#lightBox\").hide();\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("         </script>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
